export type Tone = "gold" | "teal" | "copper" | "slate";

export const executiveHighlights = [
  {
    label: "Inventario premium",
    value: "MXN 342.8M",
    note: "61% del inventario esta en ticket alto",
  },
  {
    label: "Captacion viva",
    value: "18 exclusivas",
    note: "5 nuevas conversaciones con propietarios esta semana",
  },
  {
    label: "Integraciones futuras",
    value: "EasyBroker + Inmuebles24",
    note: "Arquitectura lista para conectores y homologacion",
  },
];

export const dashboardMetrics = [
  {
    label: "Propiedades activas",
    value: "128",
    note: "+12 vs. febrero",
    tone: "gold" as Tone,
  },
  {
    label: "Propiedades en venta",
    value: "74",
    note: "Ticket medio MXN 21.4M",
    tone: "copper" as Tone,
  },
  {
    label: "Propiedades en renta",
    value: "39",
    note: "Absorcion promedio 27 dias",
    tone: "teal" as Tone,
  },
  {
    label: "Propietarios activos",
    value: "63",
    note: "18 con exclusividad premium",
    tone: "slate" as Tone,
  },
  {
    label: "Compradores calificados",
    value: "51",
    note: "22 con ventana de cierre < 60 dias",
    tone: "gold" as Tone,
  },
  {
    label: "Inversionistas activos",
    value: "18",
    note: "4 mercados internacionales en seguimiento",
    tone: "teal" as Tone,
  },
  {
    label: "Visitas programadas",
    value: "26",
    note: "9 confirmadas para este fin de semana",
    tone: "copper" as Tone,
  },
  {
    label: "Valor total del inventario",
    value: "MXN 342.8M",
    note: "Portafolio mixto venta + renta",
    tone: "gold" as Tone,
  },
];

export const properties = [
  {
    code: "CBR-POL-482",
    property: "Residencia Ruben Dario 225",
    operation: "Venta",
    price: "MXN 48.5M",
    zone: "Polanco",
    origin: "Captacion directa",
    broker: "Andrea Salgado",
    status: "Exclusiva premium",
    tone: "gold" as Tone,
    image: "/assets/images/listing/img_68.jpg",
    specs: "4 recamaras · 580 m2 · terraza privada",
  },
  {
    code: "CBR-ROM-317",
    property: "Penthouse Alvaro Obregon",
    operation: "Venta",
    price: "MXN 21.8M",
    zone: "Roma Norte",
    origin: "EasyBroker",
    broker: "Luis Cervantes",
    status: "Due diligence",
    tone: "copper" as Tone,
    image: "/assets/images/listing/img_63.jpg",
    specs: "3 recamaras · roof garden · 310 m2",
  },
  {
    code: "CBR-CON-204",
    property: "Departamento Parque Espana",
    operation: "Renta",
    price: "MXN 95K / mes",
    zone: "Condesa",
    origin: "Broker aliado",
    broker: "Sofia Mendoza",
    status: "Visitas activas",
    tone: "teal" as Tone,
    image: "/assets/images/listing/img_56.jpg",
    specs: "2 recamaras · 190 m2 · amueblado",
  },
  {
    code: "CBR-SFE-118",
    property: "Oficina Reforma Santa Fe",
    operation: "Renta",
    price: "USD 14K / mes",
    zone: "Santa Fe",
    origin: "Inmuebles24",
    broker: "Mariana Torres",
    status: "Carta de intencion",
    tone: "copper" as Tone,
    image: "/assets/images/listing/img_61.jpg",
    specs: "610 m2 · piso completo · corporativo",
  },
  {
    code: "CBR-BCH-090",
    property: "Casa Bosques de las Lomas",
    operation: "Venta",
    price: "MXN 64M",
    zone: "Bosques",
    origin: "Captacion directa",
    broker: "Javier Cervantes",
    status: "Oferta emitida",
    tone: "gold" as Tone,
    image: "/assets/images/listing/img_71.jpg",
    specs: "5 recamaras · 740 m2 · jardin",
  },
  {
    code: "CBR-NAP-061",
    property: "Loft Insurgentes WTC",
    operation: "Renta",
    price: "MXN 48K / mes",
    zone: "Napoles",
    origin: "CSV / Excel",
    broker: "Esteban Rios",
    status: "Calificando demanda",
    tone: "slate" as Tone,
    image: "/assets/images/listing/img_52.jpg",
    specs: "1 recamara · 98 m2 · business stay",
  },
  {
    code: "CBR-IND-021",
    property: "Terreno industrial Cuautitlan",
    operation: "Venta",
    price: "MXN 39.2M",
    zone: "Cuautitlan",
    origin: "Broker aliado",
    broker: "Andrea Salgado",
    status: "Negociacion",
    tone: "copper" as Tone,
    image: "/assets/images/listing/img_55.jpg",
    specs: "6,200 m2 · uso mixto · logistica",
  },
  {
    code: "CBR-POL-510",
    property: "Suite Aristoteles 88",
    operation: "Venta",
    price: "USD 1.95M",
    zone: "Polanco",
    origin: "EasyBroker",
    broker: "Mariana Torres",
    status: "Visita VIP agendada",
    tone: "teal" as Tone,
    image: "/assets/images/listing/img_72.jpg",
    specs: "3 recamaras · 265 m2 · lobby privado",
  },
];

export const recentLeads = [
  {
    name: "Maria Elizondo",
    intent: "Compra patrimonial",
    budget: "MXN 24M - 28M",
    source: "Referido privado",
    score: "A+",
    tone: "gold" as Tone,
  },
  {
    name: "Hudson Crest Family Office",
    intent: "Portafolio residencial",
    budget: "USD 5.2M",
    source: "Investor desk",
    score: "A",
    tone: "teal" as Tone,
  },
  {
    name: "Sebastian Arroyo",
    intent: "Renta ejecutiva",
    budget: "MXN 85K / mes",
    source: "Instagram private inquiry",
    score: "B+",
    tone: "slate" as Tone,
  },
  {
    name: "North Maple Holdings",
    intent: "Multifamily",
    budget: "USD 3.8M",
    source: "Roadshow Toronto",
    score: "A",
    tone: "copper" as Tone,
  },
];

export const upcomingVisits = [
  {
    property: "Residencia Ruben Dario 225",
    client: "Maria Elizondo",
    date: "14 Mar · 11:00",
    advisor: "Sofia Mendoza",
    status: "Confirmada",
    tone: "teal" as Tone,
  },
  {
    property: "Suite Aristoteles 88",
    client: "Hudson Crest Family Office",
    date: "14 Mar · 16:30",
    advisor: "Javier Cervantes",
    status: "VIP",
    tone: "gold" as Tone,
  },
  {
    property: "Departamento Parque Espana",
    client: "Sebastian Arroyo",
    date: "15 Mar · 10:00",
    advisor: "Esteban Rios",
    status: "Pendiente de confirmacion",
    tone: "copper" as Tone,
  },
  {
    property: "Casa Bosques de las Lomas",
    client: "Claudia Henao",
    date: "16 Mar · 13:15",
    advisor: "Mariana Torres",
    status: "Ruta cerrada",
    tone: "slate" as Tone,
  },
];

export const hotOpportunities = [
  {
    title: "Ruben Dario 225 + Maria Elizondo",
    value: "MXN 48.5M",
    probability: 82,
    nextStep: "Visita privada y propuesta economica",
    tone: "gold" as Tone,
  },
  {
    title: "Bosques de las Lomas + Claudia Henao",
    value: "MXN 64M",
    probability: 71,
    nextStep: "Revisar term sheet con abogado patrimonial",
    tone: "copper" as Tone,
  },
  {
    title: "Aristoteles 88 + Hudson Crest",
    value: "USD 1.95M",
    probability: 66,
    nextStep: "Enviar data room y comparativo de rentabilidad",
    tone: "teal" as Tone,
  },
];

export const zoneInventory = [
  {
    zone: "Polanco",
    active: 28,
    share: 78,
    split: "18 venta / 10 renta",
  },
  {
    zone: "Roma Norte",
    active: 19,
    share: 53,
    split: "11 venta / 8 renta",
  },
  {
    zone: "Condesa",
    active: 14,
    share: 46,
    split: "5 venta / 9 renta",
  },
  {
    zone: "Bosques",
    active: 12,
    share: 41,
    split: "10 venta / 2 renta",
  },
  {
    zone: "Santa Fe",
    active: 9,
    share: 32,
    split: "4 venta / 5 renta",
  },
];

export const advisorPerformance = [
  {
    advisor: "Javier Cervantes",
    closings: 4,
    pipeline: "MXN 112M",
    visits: 9,
    tone: "gold" as Tone,
  },
  {
    advisor: "Mariana Torres",
    closings: 3,
    pipeline: "MXN 76M",
    visits: 7,
    tone: "teal" as Tone,
  },
  {
    advisor: "Andrea Salgado",
    closings: 2,
    pipeline: "MXN 54M",
    visits: 6,
    tone: "copper" as Tone,
  },
  {
    advisor: "Sofia Mendoza",
    closings: 2,
    pipeline: "MXN 42M",
    visits: 8,
    tone: "slate" as Tone,
  },
];

export const owners = [
  {
    name: "Carlos de la Vega",
    contact: "carlos.v@cbr.mx · +52 55 1160 2401",
    linkedProperties: 3,
    exclusivity: "Exclusiva",
    status: "Activo",
    lastInteraction: "11 Mar 2026 · revision de oferta",
    zoneFocus: "Polanco · Lomas",
    advisor: "Javier Cervantes",
    tone: "gold" as Tone,
  },
  {
    name: "Patricia Landeros",
    contact: "patricia.l@cbr.mx · +52 55 8188 0921",
    linkedProperties: 2,
    exclusivity: "Semi exclusiva",
    status: "Activo",
    lastInteraction: "10 Mar 2026 · validacion de fotos",
    zoneFocus: "Condesa · Roma Norte",
    advisor: "Sofia Mendoza",
    tone: "teal" as Tone,
  },
  {
    name: "Grupo Novecento",
    contact: "assetdesk@novecento.com · +52 55 6634 1450",
    linkedProperties: 5,
    exclusivity: "Portafolio compartido",
    status: "En negociacion",
    lastInteraction: "08 Mar 2026 · terminos de honorarios",
    zoneFocus: "Santa Fe · Reforma",
    advisor: "Andrea Salgado",
    tone: "copper" as Tone,
  },
  {
    name: "Lorena Cardenas",
    contact: "lorena.cardenas@cbr.mx · +52 55 9871 2033",
    linkedProperties: 1,
    exclusivity: "Exclusiva",
    status: "Activo",
    lastInteraction: "07 Mar 2026 · feedback de visitas",
    zoneFocus: "Bosques",
    advisor: "Mariana Torres",
    tone: "gold" as Tone,
  },
  {
    name: "Esteban Pujol",
    contact: "esteban.p@cbr.mx · +52 55 4201 1180",
    linkedProperties: 2,
    exclusivity: "Abierta",
    status: "En enfriamiento",
    lastInteraction: "05 Mar 2026 · pendiente firma de autorizacion",
    zoneFocus: "Napoles · Del Valle",
    advisor: "Luis Cervantes",
    tone: "slate" as Tone,
  },
  {
    name: "Martha Dominguez",
    contact: "martha.d@cbr.mx · +52 55 7420 5421",
    linkedProperties: 4,
    exclusivity: "Exclusiva",
    status: "Renovacion de mandato",
    lastInteraction: "04 Mar 2026 · renovacion anual",
    zoneFocus: "Polanco · Anzures",
    advisor: "Javier Cervantes",
    tone: "teal" as Tone,
  },
];

export const buyers = [
  {
    name: "Maria Elizondo",
    budget: "MXN 24M - 28M",
    zones: ["Polanco", "Lomas", "Bosques"],
    propertyType: "Departamento premium",
    qualification: "A+",
    advisor: "Sofia Mendoza",
    suggested: ["CBR-POL-510", "CBR-POL-482"],
    note: "Decision patrimonial en 45 dias",
    tone: "gold" as Tone,
  },
  {
    name: "Sebastian Arroyo",
    budget: "MXN 70K - 90K / mes",
    zones: ["Condesa", "Roma Norte"],
    propertyType: "Renta ejecutiva",
    qualification: "B+",
    advisor: "Esteban Rios",
    suggested: ["CBR-CON-204", "CBR-NAP-061"],
    note: "Mudanza corporativa inmediata",
    tone: "slate" as Tone,
  },
  {
    name: "Claudia Henao",
    budget: "MXN 58M - 68M",
    zones: ["Bosques", "Lomas"],
    propertyType: "Casa familiar",
    qualification: "A",
    advisor: "Mariana Torres",
    suggested: ["CBR-BCH-090"],
    note: "Compra sujeta a venta previa en 30 dias",
    tone: "copper" as Tone,
  },
  {
    name: "Daniel Ochoa",
    budget: "MXN 18M - 22M",
    zones: ["Roma Norte", "Juarez"],
    propertyType: "Penthouse urbano",
    qualification: "A",
    advisor: "Andrea Salgado",
    suggested: ["CBR-ROM-317"],
    note: "Busca ticket con plusvalia y amenidades",
    tone: "teal" as Tone,
  },
  {
    name: "Grupo Arista",
    budget: "MXN 35M - 45M",
    zones: ["Santa Fe", "Polanco"],
    propertyType: "Oficina / corporativo",
    qualification: "A-",
    advisor: "Luis Cervantes",
    suggested: ["CBR-SFE-118"],
    note: "Decision comite en 2 semanas",
    tone: "gold" as Tone,
  },
];

export const investors = [
  {
    name: "Altor Capital MX",
    country: "Mexico",
    ticket: "MXN 120M",
    assetType: "Residencial boutique / land bank",
    zones: ["Polanco", "Bosques", "Lomas"],
    profile: "Patrimonial + renta",
    status: "Roadshow activo",
    sponsor: "Javier Cervantes",
    tone: "gold" as Tone,
  },
  {
    name: "North Maple Holdings",
    country: "Canada",
    ticket: "USD 3.8M",
    assetType: "Multifamily value-add",
    zones: ["Condesa", "Roma Norte", "Juarez"],
    profile: "Yield driven",
    status: "NDA firmado",
    sponsor: "Andrea Salgado",
    tone: "teal" as Tone,
  },
  {
    name: "Hudson Crest Family Office",
    country: "USA",
    ticket: "USD 5.2M",
    assetType: "Trophy residential",
    zones: ["Polanco", "Lomas"],
    profile: "Long hold",
    status: "Term sheet en revision",
    sponsor: "Javier Cervantes",
    tone: "copper" as Tone,
  },
  {
    name: "Al Noor Private Capital",
    country: "Dubai",
    ticket: "USD 8.5M",
    assetType: "Hospitality / branded residences",
    zones: ["Reforma", "Polanco", "Santa Fe"],
    profile: "Opportunistic",
    status: "Sourcing activo",
    sponsor: "Mariana Torres",
    tone: "gold" as Tone,
  },
  {
    name: "Piedra Alta Partners",
    country: "Mexico",
    ticket: "MXN 65M",
    assetType: "Industrial + last mile",
    zones: ["Cuautitlan", "Naucalpan"],
    profile: "Income producing",
    status: "Analisis de suelo",
    sponsor: "Andrea Salgado",
    tone: "slate" as Tone,
  },
];

export const pipelineStages = [
  {
    stage: "Nuevo lead",
    count: 14,
    value: "MXN 96M",
    tone: "slate" as Tone,
    deals: [
      {
        title: "Penthouse Lamartine 155",
        client: "Daniel Ochoa",
        value: "MXN 26M",
        note: "Lead de referido privado",
      },
      {
        title: "Portafolio Reforma 3 activos",
        client: "Altor Capital MX",
        value: "MXN 52M",
        note: "Solicita primer teaser",
      },
    ],
  },
  {
    stage: "Contactado",
    count: 9,
    value: "MXN 74M",
    tone: "teal" as Tone,
    deals: [
      {
        title: "Departamento Tres Picos",
        client: "Maria Elizondo",
        value: "MXN 22M",
        note: "Perfil completo y financiamiento listo",
      },
      {
        title: "Oficina corporativa Samara",
        client: "Grupo Arista",
        value: "MXN 18M",
        note: "Validacion con CFO",
      },
    ],
  },
  {
    stage: "Calificado",
    count: 7,
    value: "MXN 83M",
    tone: "gold" as Tone,
    deals: [
      {
        title: "Casa Bosques de las Lomas",
        client: "Claudia Henao",
        value: "MXN 64M",
        note: "Aprobacion patrimonial en curso",
      },
      {
        title: "Lote industrial Cuautitlan",
        client: "Piedra Alta Partners",
        value: "MXN 39.2M",
        note: "Cap rate objetivo validado",
      },
    ],
  },
  {
    stage: "Propiedades enviadas",
    count: 6,
    value: "MXN 58M",
    tone: "copper" as Tone,
    deals: [
      {
        title: "Aristoteles 88",
        client: "Hudson Crest Family Office",
        value: "USD 1.95M",
        note: "Comparativo de rentabilidad enviado",
      },
      {
        title: "Departamento Parque Espana",
        client: "Sebastian Arroyo",
        value: "MXN 95K / mes",
        note: "Solicita estacionamientos extra",
      },
    ],
  },
  {
    stage: "Visita agendada",
    count: 5,
    value: "MXN 117M",
    tone: "teal" as Tone,
    deals: [
      {
        title: "Ruben Dario 225",
        client: "Maria Elizondo",
        value: "MXN 48.5M",
        note: "Visita privada sabado 11:00",
      },
      {
        title: "Portafolio Polanco dos torres",
        client: "Al Noor Private Capital",
        value: "USD 4.1M",
        note: "Tour con interprete y analista",
      },
    ],
  },
  {
    stage: "Negociacion",
    count: 3,
    value: "MXN 88M",
    tone: "copper" as Tone,
    deals: [
      {
        title: "Casa Bosques de las Lomas",
        client: "Claudia Henao",
        value: "MXN 64M",
        note: "Contraoferta en firma",
      },
      {
        title: "Terreno industrial Cuautitlan",
        client: "Piedra Alta Partners",
        value: "MXN 39.2M",
        note: "Revision de uso de suelo",
      },
    ],
  },
  {
    stage: "Cierre",
    count: 2,
    value: "MXN 43M",
    tone: "gold" as Tone,
    deals: [
      {
        title: "Penthouse Alvaro Obregon",
        client: "Daniel Ochoa",
        value: "MXN 21.8M",
        note: "Firma notarial programada",
      },
      {
        title: "Oficina Reforma Santa Fe",
        client: "Grupo Arista",
        value: "USD 14K / mes",
        note: "Entrega de garantias y contrato",
      },
    ],
  },
];

export const visits = [
  {
    property: "Residencia Ruben Dario 225",
    client: "Maria Elizondo",
    date: "14 Mar 2026 · 11:00",
    advisor: "Sofia Mendoza",
    status: "Confirmada",
    comments: "Solicito revisar vistas, seguridad y tiempos de escrituracion.",
    tone: "teal" as Tone,
  },
  {
    property: "Suite Aristoteles 88",
    client: "Hudson Crest Family Office",
    date: "14 Mar 2026 · 16:30",
    advisor: "Javier Cervantes",
    status: "VIP",
    comments: "Tour privado con comparativo de yields y esquema de leaseback.",
    tone: "gold" as Tone,
  },
  {
    property: "Departamento Parque Espana",
    client: "Sebastian Arroyo",
    date: "15 Mar 2026 · 10:00",
    advisor: "Esteban Rios",
    status: "Pendiente",
    comments: "Esperando confirmacion del relocation manager.",
    tone: "copper" as Tone,
  },
  {
    property: "Casa Bosques de las Lomas",
    client: "Claudia Henao",
    date: "16 Mar 2026 · 13:15",
    advisor: "Mariana Torres",
    status: "Ruta cerrada",
    comments: "Se pidio mostrar family room, jardin y casa club.",
    tone: "slate" as Tone,
  },
  {
    property: "Terreno industrial Cuautitlan",
    client: "Piedra Alta Partners",
    date: "17 Mar 2026 · 09:30",
    advisor: "Andrea Salgado",
    status: "Tecnica",
    comments: "Incluye recorrido con ingeniero estructural y abogado urbano.",
    tone: "copper" as Tone,
  },
  {
    property: "Oficina Reforma Santa Fe",
    client: "Grupo Arista",
    date: "17 Mar 2026 · 17:00",
    advisor: "Luis Cervantes",
    status: "Confirmada",
    comments: "Comite de operaciones revisara accesos, estacionamiento y branding.",
    tone: "teal" as Tone,
  },
];

export const importSources = [
  {
    source: "EasyBroker",
    records: "812 fichas homologables",
    cadence: "Cada 30 min",
    status: "Conector listo para discovery",
    owner: "Data Ops",
    coverage: "Codigo, broker, precio, galeria, amenidades",
    tone: "gold" as Tone,
  },
  {
    source: "Inmuebles24",
    records: "436 publicaciones activas",
    cadence: "Batch diario",
    status: "Parsing y mapping en demo",
    owner: "Growth",
    coverage: "Lead source, telefono, zona, tipo de inmueble",
    tone: "teal" as Tone,
  },
  {
    source: "CSV / Excel",
    records: "Imports on demand",
    cadence: "Manual",
    status: "Plantillas operativas",
    owner: "Back office",
    coverage: "Catalogos legacy, propietarios, contactos, observaciones",
    tone: "slate" as Tone,
  },
  {
    source: "Captacion directa",
    records: "52 leads nuevos / mes",
    cadence: "Tiempo real",
    status: "Formulario y intake interno",
    owner: "Captacion",
    coverage: "Mandato, exclusividad, comisiones, estatus legal",
    tone: "gold" as Tone,
  },
  {
    source: "Brokers aliados",
    records: "17 partners activos",
    cadence: "Semanal",
    status: "Mesa colaborativa",
    owner: "Direccion comercial",
    coverage: "Origen, fee split, terminos, visitas cruzadas",
    tone: "copper" as Tone,
  },
];

export const reportCards = [
  {
    label: "Conversion lead a visita",
    value: "38%",
    note: "Meta abril 42%",
    tone: "gold" as Tone,
  },
  {
    label: "Ticket promedio",
    value: "MXN 18.7M",
    note: "Venta premium consolidada",
    tone: "copper" as Tone,
  },
  {
    label: "Tiempo promedio a cierre",
    value: "49 dias",
    note: "-6 dias vs. trimestre previo",
    tone: "teal" as Tone,
  },
  {
    label: "Inventario premium",
    value: "61%",
    note: "Participacion sobre el total",
    tone: "slate" as Tone,
  },
];

export const reportFlows = [
  {
    label: "Venta premium",
    share: 62,
    note: "Mayor empuje desde referidos y captacion directa",
  },
  {
    label: "Renta ejecutiva",
    share: 48,
    note: "Ciclo mas corto y alta rotacion en Condesa / Napoles",
  },
  {
    label: "Mandatos de inversion",
    share: 71,
    note: "Roadshows y family offices mueven el pipeline internacional",
  },
];

export const zoneDemand = [
  {
    zone: "Polanco",
    demand: "Alta",
    buyers: 17,
    note: "Mayor interes en tickets arriba de MXN 20M",
  },
  {
    zone: "Roma Norte",
    demand: "Alta",
    buyers: 11,
    note: "Busqueda urbana con potencial de renta",
  },
  {
    zone: "Condesa",
    demand: "Media alta",
    buyers: 9,
    note: "Renta ejecutiva y compradores end-user",
  },
  {
    zone: "Santa Fe",
    demand: "Media",
    buyers: 7,
    note: "Corporativo y multifamily",
  },
];

export const sourcePerformance = [
  {
    source: "Referidos privados",
    conversion: "44%",
    note: "Mejor calidad de lead y mayor ticket",
  },
  {
    source: "Captacion directa",
    conversion: "37%",
    note: "Excelente control de mandato y pricing",
  },
  {
    source: "EasyBroker",
    conversion: "28%",
    note: "Mayor volumen, menor depuracion inicial",
  },
  {
    source: "Brokers aliados",
    conversion: "31%",
    note: "Aumenta acceso a producto off-market",
  },
];

export const adminModules = [
  {
    title: "Usuarios y roles",
    status: "Demo ready",
    detail: "Direccion, brokers, captacion, back office e inversionistas con permisos diferenciados.",
    tone: "gold" as Tone,
  },
  {
    title: "Scoring de compradores",
    status: "Modelo parametrizable",
    detail: "Calificacion por presupuesto, urgencia, origen, documentacion y fuente de pago.",
    tone: "teal" as Tone,
  },
  {
    title: "Mandatos y exclusividad",
    status: "Workflow sugerido",
    detail: "Mandato abierto, semi exclusivo y exclusivo con alertas de renovacion.",
    tone: "copper" as Tone,
  },
  {
    title: "Integraciones",
    status: "Preparado para siguiente fase",
    detail: "EasyBroker, Inmuebles24, CSV, catalogos internos y conectores custom.",
    tone: "gold" as Tone,
  },
  {
    title: "Branding ejecutivo",
    status: "Cervantes premium",
    detail: "Reportes, fichas y tableros con identidad visual consistente para clientes privados.",
    tone: "slate" as Tone,
  },
  {
    title: "Auditoria y gobierno",
    status: "Trazabilidad estructurada",
    detail: "Bitacora de visitas, cambios de estatus, comentarios y ownership comercial.",
    tone: "teal" as Tone,
  },
];

export const roadmapItems = [
  "Integrar ingest de propiedades desde EasyBroker y brokers aliados.",
  "Unificar scoring de compradores e inversionistas con playbooks por segmento.",
  "Agregar data room por propiedad y checklist legal para cierres.",
  "Conectar reportes ejecutivos a fuentes reales y exportacion PDF de direccion.",
];
